# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Operator Controller documentation
theme:
 name: "material"
 features:
   - content.code.copy

repo_url: https://github.com/operator-framework/operator-controller

nav:
  - Home: 'index.md'
  - Components: 'components.md'
  - Tasks:
    - Adding a catalog of extensions: 'Tasks/adding-a-catalog.md'
    - Finding extensions to install: 'Tasks/exploring-available-packages.md'
    - Installing an extension: 'Tasks/installing-an-extension.md'
    - Deleting an extension: 'Tasks/uninstalling-an-extension.md'
  - References:
    - Supported extensions: 'refs//supported-extensions.md'
    - API references:
      - Operator Controller API reference: 'refs/api/operator-controller-api-reference.md'
      - CatalogD API reference: 'refs/api/catalogd-api-reference.md'
    - Catalog queries: 'refs/catalog-queries.md'
    - CRD Upgrade Safety: 'refs/crd-upgrade-safety.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
